### ISSUE TITLE
Implement other cpu instructions

### ISSUE THREAD

**Issue by Etheryen** [Rust-Lab-PJATK/hachi#17]
Total number of instructions is 34.

## Rreviously done:
- 00E0: CLS - Clear the display
- 1nnn: JP addr- Jump to location nnn
- 6xkk - LD Vx, byte - Set Vx = kk
- 7xkk - ADD Vx, byte - Set Vx = Vx + kk
- Annn - LD I, addr - Set I = nnn
- Dxyn - DRW Vx, Vy, nibble - Display n-byte sprite starting at memory location I at (Vx, Vy), set VF = collision.

## Require keypad:
- Ex9E - SKP Vx - Skip next instruction if key with the value of Vx is pressed
- ExA1 - SKNP Vx - Skip next instruction if key with the value of Vx is not pressed
- Fx0A - LD Vx, K - Wait for a key press, store the value of the key in Vx

## Todo:
- [x] 00EE: RET - Return from a subroutine
- [x] 2nnn - CALL addr - Call subroutine at nnn
- [x] 3xkk - SE Vx, byte - Skip next instruction if Vx = kk
- [x] 4xkk - SNE Vx, byte - Skip next instruction if Vx != kk
- [x] 5xy0 - SE Vx, Vy - Skip next instruction if Vx = Vy
- [x] 8xy0 - LD Vx, Vy - Set Vx = Vy
- [x] 8xy1 - OR Vx, Vy - Set Vx = Vx OR Vy
- [x] 8xy2 - AND Vx, Vy - Set Vx = Vx AND Vy
- [x] 8xy3 - XOR Vx, Vy - Set Vx = Vx XOR Vy
- [x] 8xy4 - ADD Vx, Vy - Set Vx = Vx + Vy, set VF = carry
- [x] 8xy5 - SUB Vx, Vy - Set Vx = Vx - Vy, set VF = NOT borrow
- [x] 8xy6 - SHR Vx - Set Vx = Vx SHR 1
- [x] 8xy7 - SUBN Vx, Vy - Set Vx = Vy - Vx, set VF = NOT borrow
- [x] 8xyE - SHL Vx {, Vy} - Set Vx = Vx SHL 1
- [x] 9xy0 - SNE Vx, Vy - Skip next instruction if Vx != Vy
- [x] Bnnn - JP V0, addr - Jump to location nnn + V0
- [x] Cxkk - RND Vx, byte - Set Vx = random byte AND kk
- [x] Fx07 - LD Vx, DT - Set Vx = delay timer value
- [x] Fx15 - LD DT, Vx - Set delay timer = Vx
- [x] Fx18 - LD ST, Vx - Set sound timer = Vx
- [x] Fx1E - ADD I, Vx - Set I = I + Vx
- [x] Fx29 - LD F, Vx - Set I = location of sprite for digit Vx
- [x] Fx33 - LD B, Vx - Store BCD representation of Vx in memory locations I, I+1, and I+2
- [x] Fx55 - LD [I], Vx - Store registers V0 through Vx in memory starting at location I
- [x] Fx65 - LD Vx, [I] - Read registers V0 through Vx from memory starting at location I
